apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-detector-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: edge-detector-operator
  template:
    metadata:
      labels:
        name: edge-detector-operator
    spec:
      serviceAccountName: edge-detector-operator
      containers:
        - name: edge-detector-operator
          # Replace this with the built image name
          image: docker.io/iportilla/edge-detector.operator_amd64:1.0.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "edge-detector-operator"
