apiVersion: edge-detector.com/v1
kind: Service
metadata:
  name: example-service
spec:
  # Default values copied from <project_dir>/helm-charts/edge-detector-cluster/values.yaml
  
  affinity: {}
  fullnameOverride: ""
  image:
    pullPolicy: IfNotPresent
    repository: iportilla/max-object-detector_amd64
    tag: latestpull
  ingress:
    annotations: {}
    enabled: false
    hosts:
    - chart-example.local
    paths: []
    tls: []
  nameOverride: ""
  nodeSelector: {}
  replicaCount: 1
  resources: {}
  service:
    port: 5000
    type: ClusterIP
  tolerations: []
  
